name: Java CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile

      - name: Run tests with Maven
        run: mvn test

      - name: Run specific algorithm tests
        run: |
          mvn test -Dtest=MergeSortTest
          mvn test -Dtest=QuickSortTest  
          mvn test -Dtest=DeterministicSelectTest
          mvn test -Dtest=ClosestPairTest

      - name: Test edge cases
        run: mvn test -Dtest="*Test" -DfailIfNoTests=false

      - name: Verify code compiles without warnings
        run: mvn compile -q